# Generated by Django 6.0.6 on 2026-06-06 13:28

from django.db import migrations


INITIAL_CATEGORIES = [
    {'name': '人文风光', 'slug': 'renwen', 'display_order': 1},
    {'name': '自然美景', 'slug': 'ziran', 'display_order': 2},
    {'name': '城市美景', 'slug': 'chengshi', 'display_order': 3},
    {'name': '美食分享', 'slug': 'meishi', 'display_order': 4},
]


def create_initial_categories(apps, schema_editor):
    ArticleCategory = apps.get_model('record_memories', 'ArticleCategory')
    for cat_data in INITIAL_CATEGORIES:
        ArticleCategory.objects.get_or_create(
            slug=cat_data['slug'],
            defaults=cat_data,
        )


def remove_initial_categories(apps, schema_editor):
    ArticleCategory = apps.get_model('record_memories', 'ArticleCategory')
    slugs = [cat['slug'] for cat in INITIAL_CATEGORIES]
    ArticleCategory.objects.filter(slug__in=slugs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('record_memories', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_initial_categories,
            reverse_code=remove_initial_categories,
        ),
    ]
