# Generated by Django 6.0.6 on 2026-06-06 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_memories', '0003_comment'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='article',
            name='article_status_05f1bb_idx',
        ),
        migrations.RemoveField(
            model_name='article',
            name='status',
        ),
    ]
